### PR TITLE
Remove sentence about getting credentials

### LINKED ISSUE #20: Remove 'Go to Service Credentials and save the API Key and URL for later use.' from '1. Clone the repo'
The issue #17 have not been done completely. Need to remove 'Go to Service Credentials and save the API Key and URL for later use.' from '1. Clone the repo' 
Thanks.

### PR DESCRIPTION
**Pull request by stevemar**
This sentence is not required. Closes #20

### CODE REVIEW

**Comment by stevemar** [comment]
@kyokonishito can you review this change?

**Comment by RiyaMRoy04** [comment]
@stevemart That sentence is required for local deployment. Advisable to move it to  Step "3. Run the server application locally using docker"

**Comment by stevemar** [comment]
@RiyaMRoy04 excellent point, thanks.

**Comment by kyokonishito** [comment]
Hi, I reviewed the change. It is no problem. Thanks!

**Review by rhagarty — APPROVED** [review]

**Pull request merged**
